name: ubuntu

on:
  push:
    paths-ignore:
    - '.github/workflows/**'
    - '!.github/workflows/ubuntu.yml'
  pull_request:
    paths-ignore:
    - '.github/workflows/**'
    - '!.github/workflows/ubuntu.yml'

jobs:
  ubuntu-20-04:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout libva
      uses: actions/checkout@v2
      with:
        repository: intel/libva
        path: libva
    - name: checkout libva-utils
      uses: actions/checkout@v2
      with:
        path: libva-utils
    - name: install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          libdrm-dev \
          libegl1-mesa-dev \
          libgl1-mesa-dev \
          libx11-dev \
          libxext-dev \
          libxfixes-dev \
          libwayland-dev \
          linux-image-5.4.0-54-generic \
          linux-headers-5.4.0-54-generic \
          linux-modules-extra-5.4.0-54-generic
    - name: build libva
      run: |
        cd libva
        ./autogen.sh --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu
        make -j$(nproc)
        sudo make install
    - name: build libva-utils
      run: |
        cd libva-utils
        ./autogen.sh --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu
        make -j$(nproc)
        make check
        sudo make install
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-without-markdown
        path: | 
          /usr/lib/x86_64-linux-gnu/*
          /usr/lib/*.so*
          /usr/lib/dri/*
          /usr/share/libdrim*
          /lib/ld-musl-x86_64.so.1
          /lib/libz*.so*
          /lib/firmware/amdgpu*
